### PR TITLE
Fix magic numbers

### LINKED ISSUE #40: Fix magic numbers in Weapon subclasses

### PR DESCRIPTION
**Pull request by aki2000ful**
Fixed "magic numbers" in key files. Magic Numbers: arbitrary values that may need changing in the future, so refactored to a static final constant for all such numbers.

### CODE REVIEW

**Review by roylin2000 — APPROVED** [review]
Beautiful, we love constants :D

File: src/main/java/core/inventory/items/Dagger.java [hunk 1]
```diff
@@ -22,12 +22,14 @@
...
+    static final int DAGGER_DAMAGE = 2;
+    static final int DAGGER_RANGE = 1;
 
     public Dagger(int level) {
         this.level = level;
         this.size = this.level;
-        this.range = this.level;
-        this.damage = this.level * 2;
+        this.range = this.level * DAGGER_RANGE;
+        this.damage = this.level * DAGGER_DAMAGE;
```
Comment (matrix-marker) [inline src/main/java/core/inventory/items/Dagger.java]: i think that multiplying by level makes it still a magic number, should at least rename `DAGGER_DAMAGE` to `DAGGER_DAMAGE_PER_LEVEL` then we know what the variable is actually doing, same for the others in `dagger` and `sword`

File: src/main/java/core/inventory/items/Sword.java [hunk 2]
```diff
@@ -22,12 +22,14 @@
...
+    static final int SWORD_DAMAGE = 3;
+    static final int SWORD_RANGE = 2;
 
     public Sword(int level) {
         this.level = level;
         this.size = this.level;
-        this.range = this.level * 2;
-        this.damage = this.level * 3;
+        this.range = this.level * SWORD_RANGE;
+        this.damage = this.level * SWORD_DAMAGE;
```
Comment (matrix-marker) [inline src/main/java/core/inventory/items/Sword.java]: see comment in Dagger constructor

Comment (matrix-marker) [reply src/main/java/core/inventory/items/Sword.java]: also, if `range` and `damage` weren't `final` variables, the damage + range setting should happen in the setter for level, so that they are always consistend with level

(just in case)

File: src/main/java/core/levels/LevelLoader.java [hunk 3]
```diff
@@ -12,15 +12,18 @@
 
 public class LevelLoader {
 
+    static final int NUM_ENEMIES = 5;
+    static final float UNIT_SCALE = 1 / 64f;
```
Comment (matrix-marker) [inline src/main/java/core/levels/LevelLoader.java]: should be local to `getLevel1`

File: src/main/java/core/levels/LevelManager.java [hunk 4]
```diff
@@ -28,6 +28,10 @@
     private final OrthogonalTiledMapRenderer mapRenderer;
     private final WorldEntityManager entityManager;
     private final SpriteBatch batch;
+    static final int SPAWN_BUFFER = 15;
```
Comment (matrix-marker) [inline src/main/java/core/levels/LevelManager.java]: unclear what this is for, rename or add comment

File: src/main/java/core/levels/LevelManager.java [hunk 5]
```diff
@@ -28,6 +28,10 @@
...
+    static final int VELOCITY_ITERATIONS = 6;
+    static final int POSITION_ITERATIONS = 2;
```
Comment (matrix-marker) [inline src/main/java/core/levels/LevelManager.java]: thsese can be inlined with an added comment, they are default values suggested for box2d

File: src/main/java/core/levels/LevelManager.java [hunk 6]
```diff
@@ -28,6 +28,10 @@
...
+    static final float MAX_STEP = 0.5f;
```
Comment (matrix-marker) [inline src/main/java/core/levels/LevelManager.java]: only used in `step` method, either have var there or reference what it does in the javadoc for that method (currently mentions the specific value)

also, a comment to explain what this does would help

File: src/main/java/core/presenters/levels/LevelGameplayController.java [hunk 7]
```diff
@@ -38,6 +38,8 @@
     private Box2DDebugRenderer box2DDebugRenderer;
     private HudManager hud;
     private InputController inputController;
+    static final int SWORD_LEVEL = 1;
+    static final int DAGGER_LEVEL = 1;
```
Comment (matrix-marker) [inline src/main/java/core/presenters/levels/LevelGameplayController.java]: these are for demo purposes, in fact these things should happen by adding a callback to the Player spawner in `DemoSpawners.createPlayerSpawner`

**Review by matrix-marker — CHANGES_REQUESTED** [review]
also a magic number to fix in `gamecharacter`: speed of characters

overall solid

File: src/main/java/core/inventory/items/Sword.java (hunk 2 above)
Comment (aki2000ful) [reply src/main/java/core/inventory/items/Sword.java]: Could we instead get rid of the setter for level since I don't think anything uses it (as the weapon gets instantiated with level as a parameter anyway).

Also by speed of characters in the Character class are you referring to setVelocity? Can't seem to find any hardcoded numbers.

File: src/main/java/core/presenters/levels/LevelGameplayController.java (hunk 7 above)
Comment (aki2000ful) [reply src/main/java/core/presenters/levels/LevelGameplayController.java]: Not sure if I understand which exact parts of the code need to be refactored

File: src/main/java/core/inventory/items/Sword.java (hunk 2 above)
Comment (matrix-marker) [reply src/main/java/core/inventory/items/Sword.java]: level system is pretty important I think it's worth keeping

File: src/main/java/core/presenters/levels/LevelGameplayController.java (hunk 7 above)
Comment (matrix-marker) [reply src/main/java/core/presenters/levels/LevelGameplayController.java]: should happen in a player spawn callback

**Review by matrix-marker — APPROVED** [review]
addressed own comments
